name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
    - main
  schedule:
  - cron: "30 0 * * 6"
  workflow_dispatch:

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-repoman@master
