name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
    - main
  schedule:
  - cron: "30 0 * * 6"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Continuous Integration
      run: |
        scripts/ci
